### ISSUE TITLE
Notícia duplicada

### ISSUE THREAD

**Issue by GiulianoBrizolla** [MapCon-RMC/MapCon#23]
![image](https://github.com/user-attachments/assets/61e576be-4490-4530-8807-636f11533f22)
Notícia aparece novamente após eu já ter avaliado ela em "notícias rastreadas"

**Comment by Jhouny** [comment]
@GiulianoBrizolla acho que foi um bug por causa de uma alteração que eu tinha feito. Agora é pra estar consertado, removi a notícia da seção de "notícias rastreadas".
