### ISSUE TITLE
Notícias já classificadas como protesto continuam voltando a tela inicial como notícias rastreadas

### ISSUE THREAD

**Issue by GiulianoBrizolla** [MapCon-RMC/MapCon#24]
![image](https://github.com/user-attachments/assets/2a3787a1-62f8-4d0c-bfc1-929ad3c72fd8)

**Comment by Jhouny** [comment]
Problema é devido ao rastreamento e a forma que o BD lida com a exclusão e migração de notícias. Issue relacionada à issue #3.
